### ISSUE TITLE
`RUN_` environment variables not honored 

### ISSUE THREAD

**Issue by chaospuppy** [defenseunicorns/maru-runner#68]
### Environment

Device and OS: Macbook Pro M3 Max, Sonoma 14.3  
App version: v0.10.4
Kubernetes distro being used: N/A
Other:

### Steps to reproduce

1. Using `tasks.yaml` from [README](https://github.com/defenseunicorns/maru-runner#quickstart)
3. export RUN_FOO=baz
4. `uds run echo-variable`
 
### Expected result
`baz`

### Actual Result
`foo`

If `variables` block is removed, there is no output

### Visual Proof (screenshots, videos, text, etc)
![Screenshot 2024-05-07 at 9 44 24 AM](https://github.com/defenseunicorns/maru-runner/assets/39381000/18f629a6-1e8a-4967-8b63-9dd58c67d0bc)

### Additional Context

Add any other context or screenshots about the technical debt here.

**Comment by UncleGedd** [comment]
Hey @chaospuppy I think I see the issue here. Whenever Maru is vendored under UDS (ie. `uds run ...`) the syntax for prefixed env vars is slightly different; you need to use `UDS_` as opposed to `RUN_` as documented [here](https://github.com/defenseunicorns/uds-cli/blob/main/docs/runner.md#variables-set-with-environment-variables). For example, given the following `tasks.yaml`
```
variables:
  - name: FOO
    default: foo

tasks:
  - name: default
    actions:
    - cmd: echo ${FOO}
```

You can set `FOO` as follows:
```
export UDS_FOO=bar
uds run
```

^ which should output `bar`

**Comment by chaospuppy** [comment]
Ahh that makes sense, I found `UDS_` was working but was confused by [this section](https://github.com/defenseunicorns/maru-runner#variable-precedence) calling out `RUN_` specifically, but if if this repo is being mirrored from upstream then I'm not sure there's anything to do here.  Thank you!
